import { existsSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, isAbsolute, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { execa } from 'execa'

import { loadConfiguredAddons } from '../addon/loader.js'
import { createAddonRegistry } from '../addon/registry.js'
import { loadBootstrapConfig } from '../config/loader.js'
import { resolveTheme } from '../config/theme'

const MODULE_DIRECTORY = dirname(fileURLToPath(import.meta.url))
const PACKAGE_ROOT = resolve(MODULE_DIRECTORY, '../..')
const WORKSPACE_ROOT = resolve(PACKAGE_ROOT, '../..')
const DEFAULT_CONFIG_PATH = resolve(WORKSPACE_ROOT, 'config.yml')
export const TAILWIND_BROWSER_CONTRACT_PATH = resolve(
  PACKAGE_ROOT,
  '.tailwind.browser.contract.generated.css',
)

export interface TailwindBrowserContract {
  safelist: string[]
  sources: string[]
  warnings: string[]
}

function unique(items: readonly string[]): string[] {
  return Array.from(new Set(items))
}

function toTailwindSourcePath(filePath: string): string {
  const relativePath = relative(PACKAGE_ROOT, filePath)

  if (relativePath === '') {
    return '.'
  }

  return relativePath.startsWith('.') ? relativePath : `./${relativePath}`
}

function escapeCssString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

export function resolveTailwindBrowserConfigPath(configPath?: string): string {
  if (!configPath) {
    return DEFAULT_CONFIG_PATH
  }

  return isAbsolute(configPath)
    ? configPath
    : resolve(process.cwd(), configPath)
}

export async function resolveTailwindBrowserContract(
  configPath?: string,
): Promise<TailwindBrowserContract> {
  const resolvedConfigPath = resolveTailwindBrowserConfigPath(configPath)
  if (!existsSync(resolvedConfigPath)) {
    return {
      safelist: [],
      sources: [],
      warnings: [],
    }
  }

  const bootstrap = loadBootstrapConfig(resolvedConfigPath)
  const theme = await resolveTheme(bootstrap.config.theme, {
    baseDirectory: bootstrap.cwd,
  })
  const addonRegistry = createAddonRegistry()
  const addonResult = await loadConfiguredAddons({
    addons: bootstrap.config.addons,
    cwd: bootstrap.cwd,
    registry: addonRegistry,
  })
  const localAddonNames = new Set(
    bootstrap.config.addons
      .filter((addon) => addon.enabled && addon.source === 'local')
      .map((addon) => addon.name),
  )
  const localAddons = addonResult.loaded.filter((addon) =>
    localAddonNames.has(addon.manifest.name),
  )

  return {
    safelist: unique([
      ...theme.tailwindSafelist,
      ...localAddons.flatMap((addon) => addon.manifest.tailwindSafelist),
    ]).sort(),
    sources: unique([
      theme.rootDir,
      ...localAddons.map((addon) => addon.rootDir),
    ]).sort(),
    warnings: addonResult.warnings.map(
      (warning) => `${warning.addonName}: ${warning.reason}`,
    ),
  }
}

export function serializeTailwindBrowserContract(
  contract: TailwindBrowserContract,
): string {
  const lines = ['/* Generated by src/cli/build-tailwind-browser.ts */']

  for (const sourcePath of contract.sources) {
    lines.push(
      `@source "${escapeCssString(toTailwindSourcePath(sourcePath))}";`,
    )
  }

  for (const token of contract.safelist) {
    lines.push(`@source inline("${escapeCssString(token)}");`)
  }

  return `${lines.join('\n')}\n`
}

export async function writeTailwindBrowserContract(
  configPath?: string,
): Promise<TailwindBrowserContract> {
  const contract = await resolveTailwindBrowserContract(configPath)
  writeFileSync(
    TAILWIND_BROWSER_CONTRACT_PATH,
    serializeTailwindBrowserContract(contract),
  )
  return contract
}

export async function buildTailwindBrowserStylesheet(options?: {
  configPath?: string
}): Promise<TailwindBrowserContract> {
  const contract = await writeTailwindBrowserContract(options?.configPath)

  for (const warning of contract.warnings) {
    console.warn(`[tailwind-browser] ${warning}`)
  }

  try {
    await execa(
      'tailwindcss',
      ['-i', 'tailwind.browser.css', '-o', 'tailwind.browser.generated.css'],
      {
        cwd: PACKAGE_ROOT,
        preferLocal: true,
        stdio: 'inherit',
      },
    )
  } finally {
    rmSync(TAILWIND_BROWSER_CONTRACT_PATH, { force: true })
  }

  return contract
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const configArg = process.argv
    .slice(2)
    .find((argument) => argument.startsWith('--config='))

  const configPath = configArg ? configArg.slice('--config='.length) : undefined

  buildTailwindBrowserStylesheet({ configPath }).catch((error: unknown) => {
    console.error(error)
    process.exitCode = 1
  })
}
