packages:
  - packages/*
  - packages/addons/*
  - packages/web/astro
  - packages/web/videos

onlyBuiltDependencies:
  - "@julusian/jpeg-turbo"
  - esbuild
  - get-windows
  - lefthook
  - node-hid
  - sharp
  - usocket
