import { z } from "zod"

import { isIconSource } from "@/core/icon-source"

export const TriggerSchema = z
  .object({
    process_name: z.union([z.string(), z.array(z.string()).min(1)]).optional(),
    window_name: z.union([z.string(), z.array(z.string()).min(1)]).optional(),
  })
  .strict()
  .refine((t) => t.process_name !== undefined || t.window_name !== undefined, {
    message: "trigger requires at least one of `process_name` or `window_name`",
  })

export const ButtonActionsSchema = z
  .object({
    tap: z.string().min(1).optional(),
    dbltap: z.string().min(1).optional(),
    hold: z.string().min(1).optional(),
  })
  .strict()

export type ButtonActions = z.infer<typeof ButtonActionsSchema>

/**
 * Runtime icon source. Accepted shapes:
 *   - `icon://<name>` — Lucide icon by name (resolved at render time)
 *   - `asset://<id>`  — pre-resolved asset id from the registry
 *   - a single emoji (Presentation or base+VS16 like ✈️)
 *
 * Anything else is rejected at config-load time so typos surface before
 * the daemon starts. The runtime also has a fallback path (alert-circle
 * Lucide icon) so an invalid source that's slipped through can't crash
 * the render tree.
 */
export const IconSourceSchema = z.string().min(1).refine(isIconSource, {
  message:
    "icon must be icon://<name>, asset://<id>, or a single emoji (one Presentation character or one base+VS16 like ✈️)",
})

export const ButtonConfigSchema = z.record(z.string(), z.unknown()).optional()

export const ButtonDefSchema = z
  .object({
    position: z.number().int().nonnegative().optional(),
    type: z.string().min(1),
    config: ButtonConfigSchema,
    accent: z.string().optional(),
    background: z.string().optional(),
    actions: ButtonActionsSchema.optional(),
  })
  .strict()

export const ButtonEntrySchema = z.union([ButtonDefSchema, z.string()])

export const DeckDefSchema = z
  .object({
    name: z.string().min(1).optional(),
    icon: IconSourceSchema.optional(),
    background: z.string().min(1).optional(),
    paginated: z.boolean().optional(),
    trigger: TriggerSchema.optional(),
    autoShow: z.boolean().optional(),
    buttons: z.array(ButtonEntrySchema),
  })
  .strict()

export const AddonEntrySchema = z.union([
  z.string().min(1),
  z
    .object({
      source: z.string().min(1),
      enabled: z.boolean().optional(),
    })
    .strict(),
])

export const LoggingSchema = z
  .object({
    level: z
      .enum(["trace", "debug", "info", "warn", "error", "fatal", "silent"])
      .optional(),
    verbose: z.boolean().optional(),
  })
  .strict()
  .optional()

export const LockSchema = z
  .object({
    buttons: z.array(ButtonDefSchema).optional(),
  })
  .strict()
  .optional()

export const ThemeEntrySchema = z.union([
  z.string().min(1),
  z
    .object({
      name: z.string().min(1).optional(),
      path: z.string().min(1),
    })
    .strict(),
])

export const AddonOverlayOverrideSchema = z
  .object({
    addon: z.string().min(1),
    autoShow: z.boolean().optional(),
    name: z.string().min(1).optional(),
    icon: IconSourceSchema.optional(),
    trigger: TriggerSchema.optional(),
    config: z.record(z.string(), z.unknown()).optional(),
  })
  .strict()

/**
 * Per-deck override for a deck generated by a loaded addon. The deck id is
 * the key in the parent record; the override applies on top of whatever the
 * addon's `createDecks` factory returned.
 */
export const AddonOverlayDeckOverridesSchema = z.record(
  z.string(),
  AddonOverlayOverrideSchema,
)

/**
 * An entry under the top-level `overlay:` key. Two variants:
 *  - user overlay deck: full DeckDef with a required `trigger`. The key in
 *    the parent record is the deck id.
 *  - addon override section: a record keyed by addon-deck-id
 *    (the id returned by the addon's `createDecks` factory). Each value is
 *    an override applied on top of the addon's defaults.
 */
export const OverlayDeckEntrySchema = z.union([
  DeckDefSchema.extend({ trigger: TriggerSchema }).strict(),
  AddonOverlayDeckOverridesSchema,
])

export const OverlayConfigSchema = z
  .record(z.string(), OverlayDeckEntrySchema)
  .optional()

export const RawConfigSchema = z
  .object({
    theme: ThemeEntrySchema.optional(),
    logging: LoggingSchema,
    decks: z.record(z.string(), DeckDefSchema),
    overlay: OverlayConfigSchema,
    addons: z.array(AddonEntrySchema).optional(),
    lock: LockSchema,
  })
  .strict()

export type RawButtonDef = z.infer<typeof ButtonDefSchema>
export type RawButtonEntry = z.infer<typeof ButtonEntrySchema>
export type RawDeckDef = z.infer<typeof DeckDefSchema>
export type RawAddonEntry = z.infer<typeof AddonEntrySchema>
export type RawConfig = z.infer<typeof RawConfigSchema>
export type TriggerDef = z.infer<typeof TriggerSchema>
export type ThemeEntry = z.infer<typeof ThemeEntrySchema>
