export {
  helloMessageSchema,
  helloAckMessageSchema,
  deckConfigMessageSchema,
  stateMessageSchema,
  decksListMessageSchema,
  showOverlayMessageSchema,
  buttonActionMessageSchema,
  methodCallMessageSchema,
  methodCallResultMessageSchema,
  selectDeckMessageSchema,
  deckActiveMessageSchema,
  dismissOverlayMessageSchema,
  wsMessageSchema,
  PROTOCOL_VERSION,
} from "./protocol-internal.ts";

export type {
  HelloMessage,
  HelloAckMessage,
  DeckConfigMessage,
  StateMessage,
  DecksListMessage,
  ShowOverlayMessage,
  ButtonActionMessage,
  MethodCallMessage,
  MethodCallResultMessage,
  SelectDeckMessage,
  DeckActiveMessage,
  DismissOverlayMessage,
  WsMessage,
} from "./protocol-internal.ts";
