// Generated by the sirenoDeck2 vite plugin — inert browser stub for a
// Node-only dependency imported by third-party addon source graphs.
// Never call these: they exist only so module evaluation succeeds.
const noop = () => {}
const proxy = new Proxy(noop, { get: () => noop })
export const join = noop
