#!/usr/bin/env node
// packages/web/scripts/capture-decks.mjs
//
// REAL deck captures via live daemon + Playwright. Click-through navigation
// with 3s settle after every deck change, fake agents when needed, and
// per-theme reboot with theme-correctness verification.
//
// Outputs (deck-only crops via .grid[data-deck-id]):
//   web-snapshot-*.png        — sparse button-type decks (main per type)
//   web-snapshot-color-*.png  — media deck tinted per buttonColor
//   overlay-{app}.png         — per-app overlay decks (vscode, chrome…)
//   coding-agents deck captures (summary + agents-p1 with fake agents)
//   01-default.png / 13-light / 14-riptide / 15-neon-grids (theme aliases)
//   demo-* legacy alias kept for back-compat where referenced
//
// Run: pnpm --filter sirenodeck-web run sync-captures

import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { spawn } from "node:child_process"
import { createRequire } from "node:module"

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(here, "..", "..", "..")
const outDir = resolve(repoRoot, "packages/web/astro/public/captures")
mkdirSync(outDir, { recursive: true })

const cliPkg = resolve(repoRoot, "packages/cli/package.json")
const requireFromCli = createRequire(cliPkg)
const { chromium } = requireFromCli("playwright")

// ---------------------------------------------------------------------------
// Theme table
const THEMES = [
  { id: "default", theme: "default", alias: "01-default.png" },
  { id: "light", theme: "light", alias: "13-light.png" },
  {
    id: "riptide",
    theme: "./packages/themes/riptide",
    alias: "14-riptide.png",
  },
  {
    id: "neon-grids",
    theme: "./packages/themes/neon-grids",
    alias: "15-neon-grids.png",
  },
]

// Web-snapshot decks (one per button type) — sparse, one type at pos 5
const WEB_SNAPSHOT_DECKS = [
  "web-snapshot-media",
  "web-snapshot-core",
  "web-snapshot-weather",
  "web-snapshot-date-time",
  "web-snapshot-system-status",
  "web-snapshot-value-display",
  "web-snapshot-emoji",
  "web-snapshot-pomodoro",
  "web-snapshot-coding-agents",
]

// Color-variant decks (media layout tinted per buttonColor)
const COLOR_VARIANTS = [
  "blue",
  "green",
  "purple",
  "cyan",
  "magenta",
  "amber",
  "lime",
].map((c) => `web-snapshot-color-${c}`)

// Overlay per-app decks (generated by app-shortcuts addon)
const OVERLAY_APPS = [
  "vscode",
  "chrome",
  "slack",
  "discord",
  "teams",
  "opencode",
  "claude-code",
  "google-meet",
].map((app) => ({ id: `app-shortcuts:${app}`, file: `overlay-${app}.png` }))

const FS_PORT = 5180
const BUSY_PORTS = [52937, 5180, 52938]

const probeBusyPorts = async () => {
  const busy = []
  for (const p of BUSY_PORTS) {
    try {
      const res = await fetch(`http://127.0.0.1:${p}/`, {
        signal: AbortSignal.timeout(300),
      })
      busy.push({ port: p, status: res.status })
    } catch {
      /* free */
    }
  }
  return busy
}

const waitFor = async (url, timeoutMs) => {
  const start = Date.now()
  while (Date.now() - start < timeoutMs) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(500) })
      if (res.status < 500) return true
    } catch {
      /* not yet */
    }
    await new Promise((r) => setTimeout(r, 300))
  }
  return false
}

const writeTempConfig = (themeValue) => {
  let themeAbs = themeValue
  if (themeValue.startsWith("./") || themeValue.startsWith("../")) {
    themeAbs = resolve(repoRoot, themeValue)
  }
  const base = readFileSync(resolve(repoRoot, "config.yml"), "utf8")
  let cfg = base.replace(/^theme:.*$/m, `theme: ${themeAbs}`)
  if (!/^theme:/m.test(cfg)) cfg = `theme: ${themeAbs}\n` + cfg
  const dir = resolve(repoRoot, ".capture-configs")
  mkdirSync(dir, { recursive: true })
  const p = join(dir, "captures.yml")
  writeFileSync(p, cfg)
  return p
}

const bootDaemon = async (themeValue, fakeAgents) => {
  const cfgPath = writeTempConfig(themeValue)
  const tsxBin = resolve(repoRoot, "packages/cli/node_modules/.bin/tsx")
  const cliEntry = resolve(repoRoot, "packages/cli/src/cli/main.ts")
  const args = [
    cliEntry,
    "start",
    "--config",
    cfgPath,
    "--emulator",
    "--port",
    "53237",
    "--log-level",
    "warn",
  ]
  const proc = spawn(tsxBin, args, {
    cwd: repoRoot,
    env: {
      ...process.env,
      SIRENO_CWD: repoRoot,
      SIRENO_CAPTURE_UNLOCKED: "1",
      SIRENO_CAPTURE_FAKE_AGENTS: "1",
      TSX_TSCONFIG_PATH: resolve(repoRoot, "packages/cli/tsconfig.json"),
    },
    stdio: ["ignore", "ignore", "inherit"],
    detached: true,
  })
  const up = await waitFor(`http://127.0.0.1:${FS_PORT}/`, 90000)
  return { proc, up }
}

const cleanup = (proc) => {
  try {
    if (proc.pid !== undefined && proc.exitCode === null)
      process.kill(-proc.pid, "SIGINT")
  } catch {
    /* noop */
  }
  setTimeout(() => {
    try {
      if (proc.pid !== undefined && proc.exitCode === null)
        process.kill(-proc.pid, "SIGKILL")
    } catch {
      /* noop */
    }
  }, 5000)
}

// --- Playwright helpers ----------------------------------------------------

const SETTLE_MS = 3000

async function holdBack(page) {
  const btn = page.locator('[data-button-type="core:back"]')
  if ((await btn.count()) === 0) return false
  const box = await btn.first().boundingBox()
  if (!box) return false
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.down()
  await page.waitForTimeout(700)
  await page.mouse.up()
  await page.waitForTimeout(SETTLE_MS)
  return true
}

async function navigateToDeck(page, targetId) {
  // Click-through navigation with 3s settle. From any deck, hold back to
  // main, then to DEMOS, then to hub/index, then to target.
  // Fallback: if already on target, just settle.
  const cur = await page
    .locator(".grid[data-deck-id]")
    .first()
    .getAttribute("data-deck-id")
    .catch(() => null)
  if (cur === targetId) {
    await page.waitForTimeout(SETTLE_MS)
    return true
  }
  // Ensure we're on main
  for (let i = 0; i < 5; i++) {
    const id = await page
      .locator(".grid[data-deck-id]")
      .first()
      .getAttribute("data-deck-id")
      .catch(() => null)
    if (id === "main") break
    const ok = await holdBack(page)
    if (!ok) break
  }
  // Main → DEMOS
  const demos = page.locator("text=DEMOS").first()
  if ((await demos.count()) === 0) return false
  await demos.click()
  await page
    .waitForSelector('[data-deck-id="demo-decks-index"]', { timeout: 10000 })
    .catch(() => {})
  await page.waitForTimeout(SETTLE_MS)
  // If target is a web-snapshot deck, go via the hub
  if (targetId.startsWith("web-snapshot-")) {
    const hub = page.locator("text=Web Snapshots").first()
    if (await hub.count()) {
      await hub.click()
      await page
        .waitForSelector('[data-deck-id="web-snapshot-index"]', {
          timeout: 10000,
        })
        .catch(() => {})
      await page.waitForTimeout(SETTLE_MS)
    }
    // Click the hub button whose targetId matches (label is e.g. "Media", "Blue")
    // We map by link target; here we brute-force by iterating hub buttons
    const hubButtons = page.locator(
      '.grid[data-deck-id="web-snapshot-index"] [data-button-type="core:change-deck"]',
    )
    // Fallback to text search inside hub
    const labelMap = {
      "web-snapshot-media": "Media",
      "web-snapshot-color-blue": "Blue",
      "web-snapshot-color-green": "Green",
      "web-snapshot-color-purple": "Purple",
      "web-snapshot-color-cyan": "Cyan",
      "web-snapshot-color-magenta": "Magenta",
      "web-snapshot-color-amber": "Amber",
      "web-snapshot-color-lime": "Lime",
      "web-snapshot-core": "Core",
      "web-snapshot-weather": "Weather",
      "web-snapshot-date-time": "Date/Time",
      "web-snapshot-system-status": "System Status",
      "web-snapshot-value-display": "Values",
      "web-snapshot-emoji": "Emoji",
      "web-snapshot-pomodoro": "Pomodoro",
      "web-snapshot-coding-agents": "Agents",
    }
    const label = labelMap[targetId] ?? targetId
    const btn = page.locator(`text=${label}`).first()
    if ((await btn.count()) === 0) return false
    await btn.click()
    await page
      .waitForSelector(`[data-deck-id="${targetId}"]`, { timeout: 10000 })
      .catch(() => {})
    await page.waitForTimeout(SETTLE_MS)
    return (await page.locator(`[data-deck-id="${targetId}"]`).count()) > 0
  }
  // Direct demo-* decks via demo-decks-index
  const btn = page
    .locator(`text=${targetId.replace("demo-", "").replace(/-/g, " ")}`)
    .first()
  // Try text match; if not found try clicking any change-deck pointing to target
  return false
}

async function captureDeck(page, deckId, outName) {
  const el = page.locator(`[data-deck-id="${deckId}"]`)
  if ((await el.count()) === 0) {
    console.warn(`[capture] no element for ${deckId}`)
    return false
  }
  // Theme correctness: log computed background var
  const bg = await page.evaluate((id) => {
    const el = document.querySelector(`[data-deck-id="${CSS.escape(id)}"]`)
    return el
      ? getComputedStyle(el)
          .getPropertyValue("--sireno-color-background")
          .trim()
      : "?"
  }, deckId)
  console.log(`[capture] theme check ${deckId}: bg=${bg}`)
  const out = resolve(outDir, outName)
  await el.screenshot({ path: out })
  console.log(`[capture] ok  ${deckId} -> ${outName}`)
  return true
}

// ---------------------------------------------------------------------------

const main = async () => {
  const busy = await probeBusyPorts()
  if (busy.length > 0) {
    const list = busy.map((b) => `  - ${b.port} (HTTP ${b.status})`).join("\n")
    console.error(
      `[capture] daemon ports already bound; stop your dev daemon and try again:\n${list}\n` +
        `Expected free: 52937 (WS bridge), 5180 (frontend vite), 52938 (emulator vite).\n` +
        `Hint: pnpm --filter @sirenodeck/cli exec sireno stop`,
    )
    process.exit(2)
  }

  const browser = await chromium.launch({
    headless: true,
    args: ["--no-sandbox", "--disable-dev-shm-usage"],
  })
  let daemon = null
  try {
    // Default theme: web-snapshot + demo + overlay captures
    let boot = await bootDaemon("default", true)
    daemon = boot.proc
    if (!boot.up) {
      console.error("[capture] daemon never bound frontend port")
      return
    }
    let ctx = await browser.newContext({
      viewport: { width: 1600, height: 1000 },
      deviceScaleFactor: 2,
    })
    let page = await ctx.newPage()
    page.on("pageerror", (e) => console.error("[page:err]", e.message))
    await page.goto(`http://127.0.0.1:${FS_PORT}/`, {
      waitUntil: "domcontentloaded",
      timeout: 30000,
    })
    await page.waitForSelector('.grid[data-deck-id="main"]', { timeout: 15000 })
    await page.waitForTimeout(SETTLE_MS)

    // All web-snapshot decks
    for (const deckId of [...WEB_SNAPSHOT_DECKS, ...COLOR_VARIANTS]) {
      const ok = await navigateToDeck(page, deckId)
      if (!ok) {
        console.warn(`[capture] navigate failed for ${deckId}`)
        continue
      }
      await captureDeck(page, deckId, `${deckId}.png`)
    }

    // Coding-agents agents deck (paginated, fake agents)
    await navigateToDeck(page, "web-snapshot-coding-agents")
    await captureDeck(
      page,
      "web-snapshot-coding-agents",
      "web-snapshot-coding-agents.png",
    )
    // Also capture the generated agents deck page 1 directly if present
    try {
      await page.locator("text=Agents").first().click()
      await page.waitForTimeout(SETTLE_MS)
      const agentsId = await page
        .locator(".grid[data-deck-id]")
        .first()
        .getAttribute("data-deck-id")
      if (agentsId && agentsId.startsWith("coding-agents:")) {
        const safe = agentsId.replace(/:/g, "-")
        await page
          .locator(`[data-deck-id="${agentsId}"]`)
          .screenshot({ path: resolve(outDir, `${safe}.png`) })
        console.log(`[capture] ok  ${agentsId} -> ${safe}.png`)
      }
    } catch {}

    // Overlay per-app decks via demo-app-overlays hub
    await navigateToDeck(page, "demo-app-overlays")
    for (const app of OVERLAY_APPS) {
      try {
        const labelMap = {
          vscode: "VS Code",
          chrome: "Chrome",
          slack: "Slack",
          discord: "Discord",
          teams: "Teams",
          opencode: "OpenCode",
          "claude-code": "Claude Code",
          "google-meet": "Google Meet",
        }
        const btn = page
          .locator(`text=${labelMap[app.id.split(":")[1]] ?? app.id}`)
          .first()
        if ((await btn.count()) === 0) {
          console.warn(`[capture] no overlay button for ${app.id}`)
          continue
        }
        await btn.click()
        await page.waitForSelector(`[data-deck-id="${app.id}"]`, {
          timeout: 10000,
        })
        await page.waitForTimeout(SETTLE_MS)
        await captureDeck(page, app.id, app.file)
        await holdBack(page)
      } catch (err) {
        console.warn(`[capture] overlay ${app.id}: ${err.message}`)
        try {
          await holdBack(page)
        } catch {}
      }
    }

    await ctx.close()
    cleanup(daemon)
    await new Promise((res) => daemon.once("exit", res))
    daemon = null

    // Per-theme main captures (theme correctness via bg var)
    for (const theme of THEMES.filter((t) => t.id !== "default")) {
      const bootT = await bootDaemon(theme.theme, true)
      daemon = bootT.proc
      if (!bootT.up) {
        console.error(`[capture] theme ${theme.id} never bound`)
        cleanup(daemon)
        continue
      }
      ctx = await browser.newContext({
        viewport: { width: 1600, height: 1000 },
        deviceScaleFactor: 2,
      })
      page = await ctx.newPage()
      await page.goto(`http://127.0.0.1:${FS_PORT}/`, {
        waitUntil: "domcontentloaded",
        timeout: 30000,
      })
      await page.waitForSelector('[data-deck-id="main"]', { timeout: 15000 })
      await page.waitForTimeout(SETTLE_MS)
      const ok = await captureDeck(page, "main", `theme-${theme.id}.png`)
      if (ok) {
        copyFileSync(
          resolve(outDir, `theme-${theme.id}.png`),
          resolve(outDir, theme.alias),
        )
        console.log(`[capture] alias ${theme.alias}`)
      }
      // Also refresh 01-default on default pass (already captured above)
      await ctx.close()
      cleanup(daemon)
      await new Promise((res) => daemon.once("exit", res))
      daemon = null
    }
  } finally {
    if (daemon) {
      cleanup(daemon)
      await new Promise((res) => daemon.once("exit", res))
    }
    await browser.close()
  }
  console.log("[capture] done")
}

main().catch((err) => {
  console.error("[fatal]", err)
  process.exit(1)
})
