/**
 * addon-config-examples.ts
 *
 * Builds copy-ready config.yml fragments for each addon button type by
 * merging Zod-derived defaults (public/buttonSchemas.json — regenerated by
 * packages/web/scripts/extract-addon-schemas.mjs) with structural
 * placeholders for required-but-undefined fields.
 */
import buttonSchemasJson from "../content/buttonSchemas.json"

type JsonObj = { [key: string]: any }

export interface SchemaEntry {
  jsonSchema?: JsonObj
  example?: JsonObj
}

const allSchemas: Record<string, SchemaEntry> = {}
Object.assign(allSchemas, buttonSchemasJson)

const q = (s: string): string =>
  /^[A-Za-z0-9_.\-/: ]+$/.test(s) ? s : `'${s.replace(/'/g, "''")}'`

const yamlScalar = (v: any): string => {
  if (v === null) return "null"
  if (typeof v === "boolean" || typeof v === "number") return String(v)
  if (typeof v === "string") {
    if (/^icon:\/\//.test(v)) return v.slice(6)
    return q(v)
  }
  return String(v)
}

const yamlLines = (obj: JsonObj, depth = 0): string[] =>
  Object.entries(obj).flatMap(([k, v]) => {
    const pad = "  ".repeat(depth)
    if (Array.isArray(v)) {
      return v.map((x) => `${pad}- ${yamlScalar(x)}`)
    }
    if (typeof v === "object" && v !== null) {
      const inner = yamlLines(v as JsonObj, depth + 1)
      return inner.length > 0 ? [`${pad}${k}:`, ...inner] : [`${pad}${k}: {}`]
    }
    return [`${pad}${k}: ${yamlScalar(v)}`]
  })

/** Placeholder for required fields that have no default/example value. */
const placeholderFor = (schema?: JsonObj): string => {
  if (!schema || typeof schema !== "object") return "~"
  if ("default" in schema && schema.default !== undefined)
    return yamlScalar(schema.default)
  if (Array.isArray(schema.enum)) return q(String(schema.enum[0]))
  const opt = (schema.oneOf ?? schema.anyOf)?.[0]
  if (opt) return placeholderFor(opt)
  switch (schema.type) {
    case "string":
      return "<string>"
    case "number":
    case "integer":
      return "<0>"
    case "boolean":
      return "<false>"
    case "array":
      return "[]"
    default:
      if (schema.type === "object") return "{}"
      return "~"
  }
}

const stripUndefinedDeep = (v: any): any => {
  if (Array.isArray(v)) return v.map(stripUndefinedDeep)
  if (typeof v === "object" && v !== null) {
    const out: JsonObj = {}
    for (const [k, val] of Object.entries(v)) {
      if (val !== undefined) out[k] = stripUndefinedDeep(val)
    }
    return out
  }
  return v
}

export interface TypeBlock {
  typeId: string
  /** Fully-rendered YAML body (already indented one level), or null when the button takes no config. */
  body: string | null
}

export const buttonTypeBlocks = (buttonTypes: readonly string[]): TypeBlock[] =>
  buttonTypes.map((typeId) => {
    const s = allSchemas[typeId]
    if (!s?.jsonSchema) return { typeId, body: null }
    const props = s.jsonSchema.properties ?? {}
    const required: Set<string> = new Set(s.jsonSchema.required ?? [])
    const merged: JsonObj = {}
    for (const [k, pschema] of Object.entries(props as JsonObj)) {
      const ex = s.example?.[k]
      merged[k] =
        ex !== undefined
          ? stripUndefinedDeep(ex)
          : required.has(k)
            ? String(placeholderFor(pschema)).replace(/<|>/g, "")
            : placeholderFor(pschema)
    }
    const lines = yamlLines(merged)
    return { typeId, body: lines.length > 0 ? lines.join("\n") : null }
  })
